"""
Comprehensive keyword database for SCAM and DANGER categories.
Contains 1000+ keywords per category across many subcategories for high-accuracy classification.
Keywords serve as semantic anchor points for embedding-based similarity matching.
"""

KEYWORDS_DATABASE = {
    "SCAM": {
        # =====================================================================
        # INVESTMENT & FINANCIAL SCAMS
        # =====================================================================
        "investment_fraud": [
            "pyramid scheme", "ponzi scheme", "mlm", "multi-level marketing",
            "guaranteed returns", "risk-free investment", "guaranteed profit",
            "unrealistic returns", "passive income", "get rich quick",
            "quick money", "easy money", "fast cash", "no risk",
            "guaranteed income", "double your money", "triple your returns",
            "investment opportunity", "investment scheme", "financial opportunity",
            "forex scam", "forex trading scam", "day trading fraud", "penny stocks",
            "pump and dump", "stock manipulation", "insider trading",
            "cryptocurrency scam", "bitcoin scam", "crypto fraud",
            "ico fraud", "token scam", "defi scam", "nft scam",
            "binary options", "binary options scam", "options trading scam",
            "high yield investment program", "hyip", "offshore investment",
            "unregistered securities", "unlicensed broker", "fake broker",
            "clone firm", "boiler room", "cold call investment",
            "advance fee fraud", "pre-ipo scam", "private placement scam",
            "commodities scam", "gold scam", "precious metals fraud",
            "real estate investment scam", "timeshare scam", "land banking scam",
            "foreign exchange fraud", "spread betting scam",
            "hedge fund fraud", "mutual fund fraud", "fake portfolio",
            "investment advisor fraud", "financial planner scam",
            "retirement scam", "pension scam", "401k scam",
            "social trading scam", "copy trading fraud", "mirror trading scam",
            "metaverse investment scam", "virtual land scam",
            "yield farming scam", "liquidity pool scam", "rug pull",
            "smart contract exploit", "token rug pull", "meme coin scam",
            "staking scam", "mining scam", "cloud mining fraud",
            "fake exchange", "fake trading platform", "phantom wallet",
            "seed phrase theft", "wallet drainer", "airdrop scam",
            "fake dividend", "dividend scam", "profit sharing scam",
            "crowdfunding fraud", "fake startup investment",
            "angel investment scam", "venture capital fraud",
        ],

        # =====================================================================
        # ROMANCE & RELATIONSHIP SCAMS
        # =====================================================================
        "romance_scam": [
            "romance scam", "catfish", "catfishing", "fake profile",
            "fake identity", "military romance", "soldier scam",
            "deployed overseas", "love scammer", "fake relationship",
            "emotional manipulation", "western union", "money transfer",
            "wire transfer needed", "urgent money", "emergency funds",
            "medical emergency scam", "family emergency scam",
            "immigration fees", "travel expenses", "visa fees",
            "ticket payment", "hotel booking scam",
            "sugar daddy scam", "sugar mommy scam", "dating scam",
            "online dating fraud", "tinder scam", "bumble scam",
            "match scam", "hinge scam", "dating app fraud",
            "fake military deployment", "oil rig scam", "engineer abroad scam",
            "customs fee scam", "inheritance from partner", "gift card romance",
            "video call refusal", "won't meet in person", "always excuses",
            "love bombing", "too good to be true profile", "stolen photos",
            "reverse image search catfish", "pig butchering scam",
            "crypto romance scam", "investment romance hybrid",
            "sextortion", "intimate image blackmail", "revenge threat scam",
            "fake wedding plans", "engagement scam",
            "widow widower scam", "lonely heart fraud",
            "dating extortion", "romance baiting",
            "fake military officer", "fake doctor abroad",
            "fake UN worker", "humanitarian worker scam",
        ],

        # =====================================================================
        # LOTTERY, PRIZE & SWEEPSTAKES SCAMS
        # =====================================================================
        "lottery_scam": [
            "lottery scam", "you won", "claim your prize",
            "congratulations you won", "lottery winner", "prize money",
            "claim lottery", "guaranteed prize", "verify your win",
            "confirm lottery win", "claim prize", "processing fee",
            "tax payment scam", "administrative fee", "claim fee",
            "verification fee", "release fee", "sweepstakes scam",
            "contest winner scam", "drawing winner", "free money",
            "surprise windfall", "unexpected inheritance",
            "foreign lottery", "international lottery", "email lottery",
            "sms lottery", "text message winner", "random selection",
            "bulk email winner", "online lottery scam",
            "nigerian lottery", "uk lottery scam", "spanish lottery",
            "el gordo scam", "euro millions scam", "mega millions scam",
            "powerball scam", "raffle scam", "lucky draw scam",
            "lucky number selected", "you have been chosen",
            "notification of award", "prize notification",
            "beneficiary notification", "unclaimed prize",
            "claim before deadline", "expiring prize",
            "agent fee", "courier fee", "delivery charge scam",
            "clearance fee", "diplomatic fee", "consignment fee",
            "winning certificate", "award certificate scam",
            "prize claim form", "lottery ticket purchase scam",
        ],

        # =====================================================================
        # PHISHING & IDENTITY THEFT
        # =====================================================================
        "phishing_fraud": [
            "phishing", "fake email", "spoof", "impersonation",
            "fake website", "phishing website", "credential theft",
            "password theft", "identity theft", "stolen identity",
            "account compromise", "verify account", "confirm account",
            "update payment", "confirm payment method", "billing issue",
            "suspicious activity notice", "unusual login", "unauthorized access",
            "click here immediately", "act now", "urgent action",
            "spear phishing", "whaling attack", "business email compromise",
            "ceo fraud", "executive impersonation", "vendor impersonation",
            "invoice redirect", "payment redirect", "bank phishing",
            "paypal phishing", "amazon phishing", "apple phishing",
            "microsoft phishing", "google phishing", "netflix phishing",
            "facebook phishing", "instagram phishing", "social media phishing",
            "smishing", "sms phishing", "vishing", "voice phishing",
            "qr code phishing", "quishing", "deepfake phishing",
            "ai generated phishing", "credential harvesting",
            "fake login page", "cloned website", "typosquatting",
            "domain spoofing", "email spoofing", "caller id spoofing",
            "man in the middle", "session hijacking", "cookie theft",
            "keylogger", "form grabber", "browser exploit",
            "fake security alert", "fake bank notification",
            "account suspension notice", "account locked notice",
            "password reset scam", "two factor bypass",
            "sim swap", "sim swapping", "phone number hijack",
            "social security scam", "ssn theft", "tax id theft",
            "medical identity theft", "insurance identity theft",
            "synthetic identity fraud", "new account fraud",
            "account takeover", "credential stuffing",
            "data breach exploitation", "leaked credentials",
            "dark web data sale", "personal data harvesting",
        ],

        # =====================================================================
        # TECH SUPPORT & SOFTWARE SCAMS
        # =====================================================================
        "tech_scam": [
            "tech support scam", "fake antivirus", "fake warning",
            "virus infected", "malware detected", "ransomware",
            "pop-up warning", "fake tech support", "scareware",
            "system infected", "system compromised", "security warning",
            "immediate action required", "call immediately", "remote access",
            "allow access", "grant permission", "download software",
            "pay for removal", "pay for fix", "subscription service scam",
            "fake microsoft support", "fake apple support",
            "fake google support", "fake geek squad",
            "fake norton support", "fake mcafee support",
            "refund scam", "overpayment scam", "refund overpayment",
            "teamviewer scam", "anydesk scam", "remote desktop scam",
            "fake driver update", "fake system optimizer",
            "fake registry cleaner", "fake disk cleanup",
            "browser locker", "screen locker", "fake blue screen",
            "fake error message", "fake crash report",
            "trojan horse", "backdoor", "spyware", "adware",
            "fake software license", "cracked software scam",
            "fake app", "malicious app", "fake update",
            "fake adobe update", "fake flash player",
            "fake browser extension", "malicious extension",
            "tech support cold call", "microsoft calling scam",
            "irs computer scam", "fbi virus scam",
            "your computer has been locked", "illegal activity detected",
            "pay fine to unlock", "webcam recording scam",
            "fake data recovery", "fake cloud backup",
            "expired warranty scam", "extended warranty robocall",
            "auto warranty scam", "vehicle service contract scam",
        ],

        # =====================================================================
        # EMPLOYMENT & WORK-FROM-HOME SCAMS
        # =====================================================================
        "employment_scam": [
            "work from home scam", "remote job scam", "easy job",
            "quick job scam", "paid easy", "cash fast",
            "money from home", "home based scam", "no experience needed",
            "no qualifications needed", "hiring scam", "job offer scam",
            "fake employer", "upfront payment job", "advance fee job",
            "application fee job", "processing fee job", "training fee scam",
            "kit fee", "envelope stuffing", "reshipping scam",
            "check cashing scam", "fake recruiter", "fake headhunter",
            "linkedin job scam", "indeed job scam", "craigslist job scam",
            "data entry scam", "typing job scam", "survey scam",
            "paid survey scam", "mystery shopper scam", "secret shopper",
            "package reshipping", "money mule", "mule recruitment",
            "fake internship", "unpaid trial scam", "trial period scam",
            "overpayment employment", "paycheck overpayment scam",
            "personal assistant scam", "virtual assistant scam",
            "nanny scam", "caregiver scam", "babysitter scam",
            "freelance scam", "upwork scam", "fiverr scam",
            "fake client", "bounced check employment",
            "commission only scam", "door-to-door scam",
            "magazine sales scam", "travel sales scam",
            "modeling scam", "talent agency scam", "acting scam",
            "casting call scam", "fake audition",
            "affiliate marketing scam", "dropshipping scam",
            "amazon fba scam", "shopify guru scam",
            "coaching scam", "mentorship scam", "mastermind scam",
            "course selling scam", "guru scam", "influencer scam",
            "social media job scam", "tiktok job scam",
            "instagram job scam", "youtube partnership scam",
            "work from home kit", "starter kit scam",
            "business opportunity scam", "franchise fraud",
        ],

        # =====================================================================
        # ADVANCE FEE & PAYMENT SCAMS
        # =====================================================================
        "advance_fee": [
            "advance fee", "upfront payment", "upfront fee",
            "processing fee", "application fee", "membership fee",
            "activation fee", "guarantee fee", "commission in advance",
            "prepayment scam", "wire transfer scam", "western union scam",
            "money gram scam", "gift card scam", "itunes card scam",
            "google play card scam", "amazon gift card payment",
            "bank transfer scam", "cryptocurrency payment scam",
            "untraceable payment", "steam card scam", "visa gift card scam",
            "walmart gift card scam", "target gift card scam",
            "escrow fraud", "fake escrow", "escrow scam",
            "pay to release funds", "pay to unlock account",
            "nigerian prince", "419 scam", "nigerian letter",
            "inheritance scam", "long lost relative scam",
            "barrister scam", "attorney scam", "lawyer scam",
            "diplomat scam", "diplomatic courier scam",
            "trunk box scam", "consignment box scam",
            "gold dust scam", "blood diamond scam",
            "dead contract scam", "dormant account scam",
            "unclaimed fund", "abandoned fund", "frozen account scam",
            "government grant scam", "free government money",
            "stimulus check scam", "covid relief scam",
            "sba loan scam", "ppp fraud", "small business grant scam",
            "fee to receive fee", "pay to get paid",
            "registration fee scam", "documentation fee scam",
            "notarization fee scam", "legalization fee scam",
            "anti-terrorism certificate scam", "money laundering certificate",
            "transfer tax scam", "foreign tax scam",
        ],

        # =====================================================================
        # ONLINE SHOPPING & E-COMMERCE SCAMS
        # =====================================================================
        "shopping_scam": [
            "payment scam", "fake payment", "fraudulent transaction",
            "stolen credit card", "credit card fraud", "card not present fraud",
            "counterfeit product", "knockoff", "fake goods",
            "imposter seller", "non-delivery", "never received",
            "wrong item received", "too good to be true",
            "unbelievable price", "below cost",
            "fake online store", "fake website shop", "scam website",
            "clone website", "fake amazon", "fake ebay",
            "fake aliexpress", "fake alibaba", "dropship scam",
            "bait and switch", "fake review", "paid review",
            "review manipulation", "fake testimonial",
            "fake tracking number", "tracking number scam",
            "empty box scam", "brick in box", "wrong product shipped",
            "fake designer", "fake luxury", "replica scam",
            "fake electronics", "fake iphone", "fake airpods",
            "fake sneakers", "fake clothing brand",
            "overcharge scam", "double billing", "hidden fees",
            "subscription trap", "free trial trap",
            "negative option billing", "auto-renewal scam",
            "fake discount", "fake coupon", "coupon scam",
            "flash sale scam", "limited time scam",
            "social media shopping scam", "instagram shop scam",
            "facebook marketplace scam", "craigslist scam",
            "offerup scam", "letgo scam", "poshmark scam",
            "mercari scam", "depop scam", "etsy scam",
            "ticket scalping scam", "fake concert ticket",
            "fake event ticket", "fake sports ticket",
            "pet scam", "puppy scam", "fake breeder",
            "fake pet adoption", "vehicle purchase scam",
            "car scam", "used car fraud", "title washing",
            "odometer rollback", "fake vehicle listing",
            "phantom vehicle", "curbstoning",
            "fake rental listing", "vacation rental scam",
            "airbnb scam", "vrbo scam", "apartment scam",
        ],

        # =====================================================================
        # PHONE & TELECOM SCAMS
        # =====================================================================
        "phone_scam": [
            "robocall scam", "automated call scam", "robo call",
            "spoofed number", "caller id spoofing", "one ring scam",
            "wangiri scam", "missed call scam", "callback scam",
            "irs phone scam", "tax phone scam", "ssa phone scam",
            "social security phone scam", "medicare phone scam",
            "insurance phone scam", "bank phone scam",
            "utility shutoff scam", "power company scam",
            "water company scam", "gas company threatening",
            "arrest warrant scam", "police calling scam",
            "dea calling scam", "fbi calling scam",
            "jury duty scam", "court summons scam",
            "bail scam", "grandparent scam", "grandchild scam",
            "family emergency call", "kidnapping ransom call",
            "virtual kidnapping", "can you hear me scam",
            "yes scam", "voice recording scam",
            "cramming", "phone bill cramming", "unauthorized charge",
            "premium rate scam", "900 number scam",
            "text message scam", "sms scam", "premium sms",
            "fake delivery notification", "package delivery scam",
            "usps text scam", "fedex text scam", "ups text scam",
            "amazon delivery scam", "dhl text scam",
            "toll road scam", "parking ticket text scam",
            "fake bank text", "fake verification code",
        ],

        # =====================================================================
        # CHARITY & DONATION SCAMS
        # =====================================================================
        "charity_scam": [
            "fake charity", "charity scam", "donation scam",
            "fraudulent charity", "bogus charity", "sham charity",
            "disaster relief scam", "hurricane relief scam",
            "earthquake relief scam", "flood relief scam",
            "pandemic charity scam", "covid charity fraud",
            "veterans charity scam", "cancer charity scam",
            "children charity scam", "animal charity scam",
            "go fund me scam", "gofundme fraud", "crowdfunding scam",
            "fake fundraiser", "fake medical fundraiser",
            "fake funeral fundraiser", "sympathy scam",
            "door-to-door charity scam", "phone solicitation scam",
            "sound alike charity", "copycat charity",
            "police charity scam", "firefighter charity scam",
            "military charity scam", "wounded warrior scam",
            "fake religious charity", "church scam", "tithing scam",
            "missionary scam", "orphanage scam",
            "tax deduction scam", "fake receipt charity",
            "emotional manipulation donation", "guilt trip donation",
            "pressure to donate", "aggressive solicitation",
        ],

        # =====================================================================
        # REAL ESTATE & RENTAL SCAMS
        # =====================================================================
        "real_estate_scam": [
            "rental scam", "fake landlord", "fake property listing",
            "apartment deposit scam", "security deposit scam",
            "application fee scam rental", "fake lease agreement",
            "phantom rental", "too cheap rental", "luxury for less",
            "subletting scam", "unauthorized sublease",
            "foreclosure scam", "mortgage scam", "loan modification scam",
            "deed theft", "title fraud", "wire fraud closing",
            "real estate wire scam", "closing cost fraud",
            "fake real estate agent", "unlicensed agent",
            "wholesaling scam", "property flip scam",
            "home repair scam", "contractor scam", "renovation fraud",
            "fake contractor", "overcharge repair",
            "moving company scam", "hostage moving scam",
            "storage unit scam", "fake storage facility",
            "property tax scam", "fake tax lien",
            "hoa scam", "fake homeowners association",
            "home inspection scam", "fake appraisal",
            "equity stripping", "reverse mortgage scam",
            "land sale scam", "vacant lot scam",
            "timeshare exit scam", "timeshare resale scam",
        ],

        # =====================================================================
        # HEALTH & WELLNESS SCAMS
        # =====================================================================
        "health_scam": [
            "miracle cure", "guaranteed cure", "cure all",
            "wonder drug", "secret remedy", "ancient remedy",
            "weight loss miracle", "fat burner scam", "diet pill scam",
            "detox scam", "cleanse scam", "anti-aging scam",
            "fake supplement", "fake vitamin", "unproven treatment",
            "alternative medicine scam", "homeopathy fraud",
            "fake cancer cure", "fake hiv cure", "fake covid cure",
            "ivermectin scam", "hydroxychloroquine scam",
            "fake vaccine", "anti-vax scam", "vaccine exemption scam",
            "fake doctor", "unlicensed practitioner", "fake clinic",
            "fake pharmacy", "counterfeit medicine", "fake pills",
            "online pharmacy scam", "prescription scam",
            "health insurance scam", "fake health plan",
            "medical billing fraud", "fake medical bill",
            "durable medical equipment scam", "dme fraud",
            "stem cell therapy scam", "regenerative therapy scam",
            "genetic testing scam", "dna test scam",
            "cosmetic surgery scam", "fake plastic surgeon",
            "dental tourism scam", "medical tourism fraud",
            "mental health scam", "fake therapist",
            "addiction treatment scam", "rehab scam",
            "fake disability claim", "disability fraud",
            "elder care scam", "nursing home fraud",
        ],

        # =====================================================================
        # GOVERNMENT & LEGAL SCAMS
        # =====================================================================
        "government_scam": [
            "irs scam", "tax scam", "fake irs", "irs impersonation",
            "tax refund scam", "stimulus scam", "ssa scam",
            "social security scam", "medicare scam", "medicaid scam",
            "fake government official", "government impersonator",
            "immigration scam", "visa scam", "green card scam",
            "fake immigration lawyer", "notario fraud",
            "deportation threat", "ice threat scam",
            "court scam", "fake court notice", "fake warrant",
            "fake jury duty", "fake subpoena", "fake summons",
            "bail bond scam", "fake fine", "pay fine now",
            "dmv scam", "fake license renewal", "fake registration",
            "fake permit", "fake inspection", "fake certification",
            "fbi scam", "dea scam", "cia scam",
            "fake federal agent", "badge number scam",
            "census scam", "fake census worker",
            "voter registration scam", "election fraud",
            "fake government grant", "free money government",
            "small business administration scam",
            "fake fema assistance", "disaster aid fraud",
            "fake embassy", "consulate scam",
            "passport renewal scam", "expedited passport scam",
        ],

        # =====================================================================
        # EDUCATION & STUDENT SCAMS
        # =====================================================================
        "education_scam": [
            "diploma mill", "fake degree", "fake university",
            "unaccredited school", "fake accreditation",
            "student loan scam", "loan forgiveness scam",
            "fake scholarship", "scholarship scam",
            "tuition payment scam", "fake financial aid",
            "essay writing scam", "term paper scam",
            "fake tutoring service", "online course scam",
            "certification scam", "fake certification",
            "coding bootcamp scam", "bootcamp fraud",
            "study abroad scam", "fake exchange program",
            "fake textbook", "textbook price gouging",
            "campus housing scam", "dorm scam",
            "student credit card scam", "student bank account scam",
            "fake internship program", "unpaid labor disguised",
            "trade school scam", "vocational school fraud",
        ],

        # =====================================================================
        # CRYPTOCURRENCY & DIGITAL ASSET SCAMS
        # =====================================================================
        "crypto_scam": [
            "rug pull", "crypto rug pull", "token rug",
            "pump and dump crypto", "shitcoin scam", "memecoin fraud",
            "fake ico", "initial coin offering scam",
            "fake ido", "fake ino", "fake token launch",
            "fake decentralized exchange", "fake dex",
            "liquidity pool drain", "flash loan attack",
            "smart contract vulnerability", "exploit",
            "fake airdrop", "airdrop phishing", "free token scam",
            "wallet connect scam", "approve all tokens",
            "unlimited approval scam", "drain wallet",
            "fake metamask", "fake trust wallet", "fake ledger",
            "seed phrase scam", "recovery phrase phishing",
            "fake crypto exchange", "exit scam exchange",
            "mt gox", "ftx fraud", "celsius scam",
            "terra luna scam", "stablecoin fraud",
            "fake staking platform", "staking reward scam",
            "bitcoin doubler", "eth doubler", "send to receive",
            "elon musk giveaway", "fake celebrity crypto",
            "fake crypto influencer", "signal group scam",
            "trading bot scam", "arbitrage bot scam",
            "fake mining hardware", "mining contract scam",
            "nft wash trading", "fake nft marketplace",
            "stolen nft", "counterfeit nft collection",
            "play to earn scam", "gamefi scam",
            "dao scam", "governance token fraud",
            "bridge exploit", "cross chain scam",
            "fake blockchain", "private blockchain scam",
        ],

        # =====================================================================
        # SOCIAL MEDIA & ONLINE SCAMS
        # =====================================================================
        "social_media_scam": [
            "fake follower scam", "buy followers", "bot followers",
            "like farming", "engagement farming", "clickbait scam",
            "fake giveaway", "follow to win scam", "share to win",
            "tag friends scam", "viral scam post",
            "facebook scam", "instagram scam", "tiktok scam",
            "twitter scam", "youtube scam", "snapchat scam",
            "linkedin scam", "pinterest scam", "reddit scam",
            "discord scam", "telegram scam", "whatsapp scam",
            "fake verified account", "impersonator account",
            "celebrity impersonation", "brand impersonation",
            "fake sponsorship", "fake brand deal",
            "influencer scam", "paid partnership scam",
            "fake product review", "fake unboxing",
            "money flipping", "cash app flip scam",
            "venmo scam", "zelle scam", "paypal scam",
            "fake payment screenshot", "payment pending scam",
            "dm scam", "inbox scam", "message request scam",
            "someone tagged you scam", "see who viewed profile",
            "free premium scam", "account upgrade scam",
            "facebook marketplace scam", "marketplace fraud",
            "fake buyer", "fake seller", "shipping label scam",
            "overpayment marketplace",
        ],

        # =====================================================================
        # INSURANCE & FINANCIAL SERVICES SCAMS
        # =====================================================================
        "insurance_scam": [
            "insurance fraud", "fake insurance policy",
            "ghost broker", "fake insurance broker",
            "fronting insurance", "staged accident",
            "fake auto insurance", "no insurance coverage",
            "health insurance scam", "fake coverage",
            "life insurance scam", "fake beneficiary",
            "travel insurance scam", "fake travel coverage",
            "pet insurance scam", "fake pet coverage",
            "warranty scam", "fake extended warranty",
            "home warranty scam", "appliance warranty fraud",
            "debt relief scam", "debt consolidation scam",
            "credit repair scam", "fake credit report",
            "credit score scam", "free credit check trap",
            "payday loan scam", "predatory lending",
            "loan shark", "illegal lending", "usury",
            "fake bank", "fake credit union", "phantom bank",
            "check washing", "counterfeit check",
            "money order scam", "cashier check fraud",
            "fake certified check", "altered check",
            "atm skimming", "card skimming", "shimming",
            "point of sale skimming", "gas pump skimmer",
            "contactless skimming", "rfid theft",
        ],

        # =====================================================================
        # TRAVEL & VACATION SCAMS
        # =====================================================================
        "travel_scam": [
            "travel scam", "fake travel agency", "bogus travel deal",
            "vacation scam", "free vacation scam", "timeshare presentation",
            "fake airline ticket", "phantom flight", "fake booking site",
            "hotel booking scam", "fake hotel reservation",
            "fake car rental", "bait switch hotel",
            "fake cruise deal", "cruise ship scam",
            "all inclusive scam", "resort scam",
            "fake tour operator", "fake excursion",
            "taxi meter scam", "overcharge taxi",
            "fake visa service", "visa expediting scam",
            "fake travel insurance", "trip cancellation scam",
            "foreign currency exchange scam", "money exchange rip off",
            "fake airport transfer", "unlicensed taxi",
            "pickpocket tourist", "distraction theft tourist",
            "fake police tourist scam", "bribe scam abroad",
            "jet ski damage scam", "rental damage scam",
            "tourist trap overpricing", "fake souvenir",
        ],

        # =====================================================================
        # ELDER & VULNERABLE PERSON SCAMS
        # =====================================================================
        "elder_scam": [
            "elder fraud", "elder abuse financial", "senior scam",
            "grandparent scam", "grandchild in trouble",
            "caregiver theft", "power of attorney abuse",
            "guardianship scam", "conservatorship fraud",
            "reverse mortgage scam", "home equity theft",
            "annuity scam", "inappropriate annuity",
            "funeral pre-payment scam", "cemetery plot scam",
            "fake anti-aging product", "miracle health cure elder",
            "sweetheart swindle", "companion scam",
            "home repair elder scam", "driveway scam",
            "roof repair scam", "chimney scam",
            "utility impersonation elder", "medicare fraud elder",
            "prescription discount scam", "drug discount card",
            "computer help elder scam", "tech support elder",
            "isolation exploitation", "financial exploitation",
            "undue influence", "diminished capacity exploitation",
        ],

        # =====================================================================
        # GENERAL FRAUD & DECEPTION KEYWORDS
        # =====================================================================
        "general_fraud": [
            "fraud", "scam", "con", "con artist", "grifter",
            "fraudulent", "deceive", "deception", "deceit",
            "trick", "trickery", "misleading", "misrepresentation",
            "fake", "counterfeit", "forged", "fabricated", "false",
            "untrue", "dishonest", "dishonesty", "corruption",
            "suspicious", "suspect", "dubious", "questionable", "sketchy",
            "shady", "untrustworthy", "unreliable", "illegitimate",
            "swindle", "swindler", "hustle", "hustler", "fleece",
            "bilk", "defraud", "cheat", "cheater", "rip off",
            "ripoff", "ripped off", "bamboozle", "hoodwink",
            "dupe", "duped", "victimize", "exploit", "exploitation",
            "predatory", "predator financial", "take advantage",
            "manipulation", "manipulate", "coerce",
            "pressure tactics", "high pressure sales", "urgency tactic",
            "fear tactic", "intimidation tactic", "false urgency",
            "limited time offer scam", "act now or lose",
            "once in a lifetime", "exclusive opportunity",
            "secret method", "insider secret", "loophole",
            "guaranteed results", "no strings attached",
            "free trial scam", "cancel anytime lie",
            "money back guarantee lie", "satisfaction guaranteed lie",
            "certified scam", "accredited fraud",
            "verified scam", "authenticated fraud",
            "official looking scam", "legitimate looking fraud",
            "too good to be true", "sounds too good",
            "if it sounds too good", "red flag", "warning sign",
            "consumer alert", "fraud alert", "scam alert",
            "report fraud", "report scam", "been scammed",
            "lost money to", "stolen money", "money gone",
            "cant get money back", "no refund", "refused refund",
            "unauthorized charge", "unauthorized transaction",
            "unauthorized withdrawal", "unauthorized transfer",
            "unknown charge", "mystery charge",
            "fine print trap", "hidden terms", "buried clause",
            "bait and switch", "false advertising",
            "deceptive marketing", "misleading claim",
            "fake endorsement", "paid testimonial",
            "astroturfing", "fake grassroots",
            "sockpuppet", "fake account", "bot account",
        ],

        # =====================================================================
        # ILLEGAL ACTIVITIES & BLACK MARKET
        # =====================================================================
        "illegal_activity": [
            "illegal", "unlicensed", "unregistered", "unauthorized",
            "black market", "underground market", "dark web marketplace",
            "tor marketplace", "money laundering", "structuring",
            "smurfing", "shell company", "fake business",
            "front company", "bribery", "corruption",
            "embezzlement", "misappropriation", "piracy",
            "counterfeiting currency", "fake bill", "fake banknote",
            "document forgery", "fake passport", "fake id",
            "fake drivers license", "fake social security card",
            "fake birth certificate", "identity document fraud",
            "human trafficking", "forced labor", "exploitation",
            "smuggling", "contraband", "illegal import",
            "tax evasion", "tax fraud", "offshore tax haven",
            "price fixing", "bid rigging", "collusion",
            "antitrust violation", "market manipulation",
            "securities fraud", "wire fraud", "mail fraud",
            "bank fraud", "mortgage fraud", "insurance fraud scheme",
            "healthcare fraud", "billing fraud", "upcoding",
            "kickback", "referral fee fraud", "commission fraud",
            "false claim", "fraudulent claim", "inflated claim",
            "phantom employee", "payroll fraud", "ghost worker",
            "procurement fraud", "contract fraud", "bid fraud",
        ],
    },

    "DANGER": {
        # =====================================================================
        # PHYSICAL INJURY & BODILY HARM
        # =====================================================================
        "physical_injury": [
            "injury", "injured", "hurt", "bleeding", "broken bone",
            "fracture", "wound", "laceration", "bruise", "trauma",
            "severe injury", "critical injury", "accident", "collision",
            "crash", "hit by", "struck by", "falling object",
            "fall from height", "electrocution", "burn", "scalding",
            "cut", "severed", "amputation", "pain", "agony",
            "suffer", "suffering", "victim", "casualty",
            "concussion", "head injury", "brain injury", "skull fracture",
            "spinal injury", "spinal cord damage", "paralysis",
            "internal bleeding", "organ damage", "ruptured organ",
            "puncture wound", "stab wound", "gunshot wound",
            "shrapnel wound", "blast injury", "crush injury",
            "crushing", "pinch point injury", "entanglement",
            "dislocation", "torn ligament", "torn muscle",
            "tendon injury", "nerve damage", "eye injury",
            "blinding", "hearing loss injury", "ear damage",
            "dental injury", "jaw fracture", "facial injury",
            "chest injury", "rib fracture", "pneumothorax",
            "abdominal injury", "pelvic fracture",
            "compound fracture", "open wound", "degloving",
            "avulsion", "road rash", "gravel rash",
            "frostbite", "hypothermia", "heat stroke",
            "heat exhaustion", "dehydration severe",
            "altitude sickness", "barotrauma",
            "decompression sickness", "bends",
            "animal bite", "dog bite", "snake bite",
            "spider bite", "insect sting severe",
            "allergic reaction severe", "anaphylaxis",
            "bee sting allergy", "wasp sting",
            "jellyfish sting", "scorpion sting",
        ],

        # =====================================================================
        # CHEMICAL & HAZARDOUS MATERIAL HAZARDS
        # =====================================================================
        "chemical_hazard": [
            "chemical", "toxic", "toxin", "poison", "poisoning",
            "hazardous", "hazardous material", "hazmat", "dangerous chemical",
            "contamination", "contaminated", "pollution", "pollutant",
            "radiation", "radioactive", "nuclear", "asbestos",
            "lead poisoning", "mercury poisoning", "pesticide",
            "insecticide", "herbicide", "fungicide",
            "solvents", "fumes", "gas leak", "carbon monoxide",
            "hydrogen sulfide", "exposure", "exposed to", "inhalation",
            "chemical burn", "acid burn", "alkaline burn",
            "hydrochloric acid", "sulfuric acid", "nitric acid",
            "caustic soda", "lye", "ammonia", "bleach hazard",
            "chlorine gas", "mustard gas", "nerve agent",
            "cyanide", "arsenic", "thallium", "ricin",
            "formaldehyde", "benzene", "toluene", "xylene",
            "acetone hazard", "methanol poisoning", "ethylene glycol",
            "antifreeze poisoning", "paint thinner fumes",
            "volatile organic compound", "voc exposure",
            "pcb contamination", "dioxin", "pfas contamination",
            "forever chemicals", "pfos", "pfoa",
            "heavy metal contamination", "cadmium", "chromium",
            "beryllium exposure", "silica dust", "silicosis",
            "asbestosis", "mesothelioma risk", "black lung",
            "coal dust", "grain dust explosion",
            "chemical spill", "hazmat spill", "toxic waste",
            "waste dump", "illegal dumping", "superfund site",
            "brownfield contamination", "groundwater contamination",
            "soil contamination", "air pollution severe",
            "industrial emission", "factory pollution",
            "chemical weapon", "biological weapon", "bioterrorism",
            "anthrax threat", "sarin gas", "vx nerve agent",
            "radiological dispersal", "dirty bomb",
            "nuclear fallout", "radiation sickness",
            "ionizing radiation", "non-ionizing radiation hazard",
            "uv radiation burn", "microwave radiation hazard",
            "radon gas", "radon contamination",
        ],

        # =====================================================================
        # WORKPLACE & OCCUPATIONAL HAZARDS
        # =====================================================================
        "workplace_danger": [
            "workplace accident", "occupational injury", "unsafe conditions",
            "unsafe workplace", "safety violation", "osha violation",
            "no safety equipment", "missing safety gear",
            "inadequate protection", "equipment failure",
            "structural damage", "unstable structure",
            "fall hazard", "electrical hazard", "fire hazard workplace",
            "machinery hazard", "equipment hazard", "unguarded equipment",
            "inadequate training", "untrained worker", "lack of supervision",
            "confined space danger", "confined space entry",
            "oxygen deficient atmosphere", "engulfment hazard",
            "trench collapse", "excavation hazard",
            "scaffolding collapse", "scaffold failure",
            "ladder fall", "ladder hazard", "unstable ladder",
            "crane accident", "crane collapse", "rigging failure",
            "forklift accident", "forklift tip over",
            "conveyor hazard", "conveyor entanglement",
            "press machine hazard", "hydraulic press danger",
            "power tool injury", "saw injury", "drill injury",
            "grinding hazard", "welding hazard", "arc flash",
            "electrical arc", "high voltage", "live wire",
            "lockout tagout violation", "loto failure",
            "energized equipment", "stored energy hazard",
            "pneumatic hazard", "hydraulic hazard",
            "compressed gas hazard", "gas cylinder danger",
            "boiler explosion", "pressure vessel failure",
            "steam burn", "hot surface burn",
            "noise hazard", "hearing damage workplace",
            "vibration hazard", "repetitive strain",
            "ergonomic hazard", "manual handling injury",
            "slip trip fall", "wet floor hazard",
            "uneven surface", "poor lighting hazard",
            "working at height", "rooftop danger",
            "construction site hazard", "demolition hazard",
            "asbestos removal hazard", "lead paint removal",
            "mining hazard", "mine collapse", "cave in",
            "tunnel collapse", "underground hazard",
            "offshore hazard", "oil rig danger", "platform hazard",
            "agricultural hazard", "farm equipment danger",
            "pto entanglement", "grain bin entrapment",
            "chemical exposure workplace", "toxic fumes workplace",
            "heat stress workplace", "cold stress workplace",
        ],

        # =====================================================================
        # VIOLENCE, WEAPONS & THREATS
        # =====================================================================
        "violence_threat": [
            "violence", "violent", "assault", "attack", "battery",
            "threat", "threatening", "hostile", "aggressive", "aggression",
            "weapon", "armed", "gun", "knife", "explosive", "bomb",
            "murder", "homicide", "killing", "death", "fatal",
            "deadly", "deadly force", "self defense", "fight", "brawl",
            "gang violence", "mob", "riot", "civil unrest",
            "mass shooting", "active shooter", "school shooting",
            "workplace violence", "domestic violence", "intimate partner violence",
            "child abuse", "child endangerment", "child neglect",
            "elder abuse", "vulnerable adult abuse",
            "hate crime", "hate attack", "bias attack",
            "racial violence", "ethnic violence", "religious violence",
            "terrorism", "terrorist attack", "extremism",
            "radical violence", "political violence", "insurgency",
            "bombing", "suicide bombing", "car bombing",
            "vehicle ramming", "vehicle attack",
            "stabbing spree", "knife attack", "machete attack",
            "arson attack", "firebombing", "molotov cocktail",
            "acid attack", "chemical attack on person",
            "poisoning someone", "deliberate contamination",
            "sniper", "ambush", "drive by shooting",
            "execution style", "targeted killing", "assassination",
            "armed robbery", "carjacking", "home invasion",
            "kidnapping", "abduction", "hostage situation",
            "ransom demand", "extortion threat",
            "rape", "sexual assault", "sexual violence",
            "molestation", "trafficking", "human trafficking",
            "forced prostitution", "sex trafficking",
            "torture", "mutilation", "dismemberment",
            "war crime", "genocide", "ethnic cleansing",
            "mass atrocity", "crimes against humanity",
            "explosive device", "ied", "improvised explosive",
            "pipe bomb", "mail bomb", "package bomb",
            "grenade", "rocket propelled grenade", "rpg",
            "firearm", "handgun", "rifle", "shotgun",
            "automatic weapon", "semi-automatic", "assault rifle",
            "ammunition", "bullet", "caliber",
            "concealed weapon", "illegal firearm", "ghost gun",
            "3d printed gun", "straw purchase firearm",
            "brass knuckles", "taser misuse", "pepper spray attack",
            "blunt force trauma", "beating", "punching",
            "kicking", "stomping", "choking", "strangling",
            "threat to kill", "death threat", "kill threat",
            "threatening letter", "threatening message",
            "cyberstalking", "online harassment",
            "doxxing", "swatting", "false report attack",
        ],

        # =====================================================================
        # HEALTH & MEDICAL EMERGENCIES
        # =====================================================================
        "health_emergency": [
            "disease", "illness", "sick", "sickness", "epidemic",
            "pandemic", "outbreak", "contagious", "infectious",
            "virus", "bacteria", "infection", "contaminated food",
            "food poisoning", "foodborne illness", "salmonella",
            "e coli", "listeria", "botulism", "norovirus",
            "toxicity", "overdose", "drug overdose",
            "medical emergency", "heart attack", "myocardial infarction",
            "stroke", "cerebrovascular accident", "cardiac arrest",
            "respiratory failure", "choking", "suffocation",
            "asphyxiation", "hospitalized", "critical condition",
            "life-threatening condition", "sepsis", "septic shock",
            "anaphylactic shock", "anaphylaxis emergency",
            "diabetic emergency", "diabetic coma", "insulin shock",
            "seizure", "epileptic seizure", "status epilepticus",
            "severe allergic reaction", "allergic shock",
            "asthma attack severe", "respiratory distress",
            "pulmonary embolism", "blood clot", "deep vein thrombosis",
            "internal hemorrhage", "hemorrhagic event",
            "meningitis", "encephalitis", "brain infection",
            "tuberculosis", "tb outbreak", "mrsa infection",
            "flesh eating bacteria", "necrotizing fasciitis",
            "ebola", "marburg virus", "hemorrhagic fever",
            "plague", "cholera", "typhoid", "malaria severe",
            "dengue hemorrhagic", "zika complication",
            "covid-19 severe", "coronavirus critical",
            "bird flu", "avian influenza", "swine flu", "h1n1",
            "rabies", "tetanus", "diphtheria",
            "whooping cough severe", "measles complication",
            "polio", "smallpox", "monkeypox severe",
            "hantavirus", "leptospirosis", "legionnaires disease",
            "toxic shock syndrome", "organ failure",
            "kidney failure acute", "liver failure acute",
            "multi-organ failure", "brain death",
            "coma", "unconscious", "unresponsive",
            "cardiac arrhythmia", "ventricular fibrillation",
            "aortic dissection", "ruptured aneurysm",
            "traumatic brain injury", "tbi severe",
            "spinal cord injury", "paralysis onset",
            "severe dehydration", "electrolyte imbalance",
            "hypothermia severe", "hyperthermia",
            "heat stroke emergency", "cold exposure",
            "near drowning", "submersion injury",
            "smoke inhalation severe", "carbon monoxide poisoning",
            "chemical poisoning", "heavy metal poisoning",
            "radiation sickness acute", "radiation poisoning",
            "suicide attempt", "self harm", "self injury",
            "mental health crisis", "psychotic episode",
            "psychiatric emergency", "suicidal ideation",
        ],

        # =====================================================================
        # NATURAL DISASTERS & EXTREME WEATHER
        # =====================================================================
        "natural_disaster": [
            "earthquake", "tsunami", "hurricane", "tornado", "cyclone",
            "flood", "flooding", "flash flood", "river flood",
            "landslide", "mudslide", "debris flow",
            "avalanche", "wildfire", "forest fire", "brush fire",
            "fire", "explosion", "gas explosion", "severe weather",
            "natural disaster", "extreme weather", "lightning strike",
            "hail storm", "blizzard", "ice storm",
            "emergency", "disaster zone", "catastrophe",
            "calamity", "crisis", "state of emergency",
            "volcanic eruption", "lava flow", "pyroclastic flow",
            "volcanic ash", "lahar", "volcanic mudflow",
            "sinkhole", "ground subsidence", "earth collapse",
            "drought severe", "water shortage", "famine",
            "heat wave extreme", "cold wave extreme",
            "polar vortex", "arctic blast", "deep freeze",
            "monsoon severe", "tropical storm", "typhoon",
            "storm surge", "coastal flooding", "tidal wave",
            "waterspout", "dust storm", "sandstorm",
            "haboob", "derecho", "microburst", "downburst",
            "supercell thunderstorm", "severe thunderstorm",
            "thunder snow", "freezing rain", "ice accumulation",
            "black ice road", "whiteout conditions",
            "fog dense", "visibility zero",
            "magnitude earthquake", "richter scale",
            "epicenter", "aftershock", "foreshock",
            "liquefaction", "ground rupture", "fault line",
            "seismic activity", "tremor", "earth tremor",
            "dam failure", "dam breach", "levee breach",
            "river overflow", "canal overflow",
            "glacial lake outburst", "jökulhlaup",
            "permafrost thaw", "coastal erosion",
            "king tide", "rogue wave", "abnormal wave",
            "geomagnetic storm", "solar flare impact",
            "space weather emergency",
        ],

        # =====================================================================
        # TRANSPORTATION & VEHICLE HAZARDS
        # =====================================================================
        "traffic_danger": [
            "traffic accident", "road accident", "car accident", "crash",
            "collision", "pile-up", "multi-vehicle", "hit and run",
            "drunk driving", "impaired driving", "reckless driving",
            "speeding", "traffic violation", "unsafe driving",
            "mechanical failure", "brake failure", "tire blowout",
            "lost control", "derailment", "plane crash",
            "maritime disaster", "pedestrian hit", "cyclist hit",
            "motorcycle accident", "truck accident", "bus accident",
            "school bus accident", "train accident", "train collision",
            "train derailment", "subway accident", "metro accident",
            "aviation accident", "aircraft malfunction",
            "helicopter crash", "small plane crash",
            "runway incursion", "near miss aviation",
            "bird strike", "engine failure aircraft",
            "emergency landing", "crash landing",
            "boat accident", "capsized boat", "sinking vessel",
            "ferry accident", "cruise ship accident",
            "cargo ship incident", "oil tanker accident",
            "jet ski accident", "kayak accident", "canoe capsized",
            "sailing accident", "sailing disaster",
            "wrong way driver", "head on collision",
            "rear end collision", "side impact",
            "t-bone collision", "rollover accident",
            "vehicle fire", "car fire", "engine fire",
            "fuel leak vehicle", "gas tank rupture",
            "airbag malfunction", "seatbelt failure",
            "child car accident", "car seat failure",
            "road rage incident", "aggressive driving",
            "distracted driving", "texting while driving",
            "drowsy driving", "fatigued driver",
            "commercial vehicle accident", "semi-truck accident",
            "18 wheeler accident", "tanker truck accident",
            "hazmat transport accident", "chemical truck spill",
            "construction zone accident", "work zone crash",
            "intersection accident", "red light running",
            "stop sign running", "yield failure",
            "bridge collapse vehicle", "overpass collapse",
            "tunnel accident", "mountain road accident",
            "cliff fall vehicle", "guardrail breach",
            "pothole damage severe", "road surface hazard",
            "black ice accident", "hydroplaning",
            "fog related crash", "dust storm crash",
            "animal on road collision", "deer strike",
        ],

        # =====================================================================
        # WATER & AQUATIC HAZARDS
        # =====================================================================
        "water_hazard": [
            "drowning", "water hazard", "dangerous water",
            "strong current", "whirlpool", "undertow",
            "riptide", "rip current", "dangerous waves",
            "thin ice", "ice hazard", "water contamination",
            "contaminated water", "sewage", "raw sewage",
            "bacteria water", "parasites water",
            "disease-ridden water", "unsanitary water", "biohazard",
            "flash flood water", "swift water rescue",
            "submerged hazard", "underwater obstacle",
            "diving accident", "scuba diving emergency",
            "decompression sickness diving", "nitrogen narcosis",
            "freediving blackout", "shallow water blackout",
            "pool drain entrapment", "pool suction hazard",
            "pool chemical hazard", "chlorine overdose pool",
            "hot tub danger", "spa bacteria",
            "blue green algae", "harmful algal bloom",
            "red tide", "cyanobacteria", "toxic algae",
            "jellyfish swarm", "shark sighting", "shark attack",
            "crocodile danger", "alligator danger",
            "hippopotamus danger", "piranha",
            "stingray", "sea urchin", "coral cut",
            "dam spillway danger", "waterfall hazard",
            "rapids class five", "whitewater danger",
            "cold water shock", "immersion hypothermia",
            "water depth unknown", "murky water",
            "irrigation canal hazard", "drainage ditch hazard",
            "mine shaft flooding", "cave flooding",
            "underground river hazard", "cenote danger",
            "tsunami warning", "storm surge flood",
            "coastal flooding danger", "high tide hazard",
            "boat wake hazard", "wake damage",
            "water skiing injury", "wakeboarding injury",
            "surfing injury", "surfing reef hazard",
        ],

        # =====================================================================
        # STRUCTURAL & BUILDING HAZARDS
        # =====================================================================
        "structural_danger": [
            "building collapse", "structural failure", "collapse",
            "unstable building", "dangerous building", "condemned building",
            "unsafe structure", "deteriorating structure", "deteriorated",
            "foundation damage", "structural damage", "crack",
            "foundation crack", "subsidence", "unstable ground",
            "unsafe stairway", "unsafe railing", "falling debris",
            "roof collapse", "ceiling collapse", "floor collapse",
            "wall collapse", "retaining wall failure",
            "balcony collapse", "deck collapse", "porch collapse",
            "parking garage collapse", "overpass collapse",
            "bridge failure", "bridge structural damage",
            "dam structural failure", "levee structural failure",
            "tunnel collapse structural", "mine shaft collapse",
            "scaffolding collapse structural", "crane collapse structural",
            "tower collapse", "antenna tower failure",
            "cell tower collapse", "wind turbine failure",
            "solar panel fall", "satellite dish fall",
            "chimney collapse", "facade failure", "cladding failure",
            "glass panel fall", "curtain wall failure",
            "elevator malfunction", "escalator malfunction",
            "elevator freefall", "elevator entrapment",
            "revolving door malfunction", "automatic door malfunction",
            "structural corrosion", "rust damage",
            "concrete spalling", "rebar exposure",
            "wood rot structural", "termite damage structural",
            "mold structural damage", "water damage structural",
            "frost heave", "ground frost damage",
            "earthquake damage building", "seismic damage",
            "wind damage building", "tornado damage building",
            "snow load collapse", "ice dam damage",
            "abandoned building hazard", "derelict building",
            "construction site hazard structural",
            "demolition hazard structural",
            "historic building deterioration",
            "overloaded structure", "excessive load",
            "vibration damage", "resonance damage",
            "pile driving damage", "nearby construction damage",
            "underground void", "sinkhole under building",
        ],

        # =====================================================================
        # FIRE, EXPLOSION & BURN HAZARDS
        # =====================================================================
        "fire_hazard": [
            "fire", "fire hazard", "flammable", "combustible", "ignition",
            "burn", "burned", "burning", "smoke inhalation", "smoke",
            "flames", "blaze", "inferno", "conflagration", "arson",
            "fire danger", "fire risk", "fire code violation",
            "no fire exits", "blocked exits", "inadequate escape route",
            "wildfire approaching", "brush fire nearby",
            "structure fire", "house fire", "apartment fire",
            "building fire", "warehouse fire", "factory fire",
            "office fire", "school fire", "hospital fire",
            "hotel fire", "nightclub fire", "theater fire",
            "vehicle fire", "car fire", "truck fire",
            "aircraft fire", "boat fire", "ship fire",
            "electrical fire", "wiring fire", "short circuit fire",
            "overloaded outlet", "extension cord fire",
            "space heater fire", "portable heater danger",
            "furnace malfunction", "boiler fire", "oven fire",
            "stove fire", "cooking fire", "grease fire",
            "deep fryer fire", "microwave fire", "toaster fire",
            "dryer fire", "lint fire", "laundry fire",
            "candle fire", "unattended flame", "open flame hazard",
            "smoking fire", "cigarette fire", "cigar fire",
            "campfire danger", "bonfire danger", "burn pit hazard",
            "fireworks accident", "fireworks injury",
            "sparkler burn", "explosive burn",
            "gas explosion", "propane explosion", "natural gas explosion",
            "dust explosion", "grain elevator explosion",
            "chemical explosion", "industrial explosion",
            "refinery explosion", "pipeline explosion",
            "transformer explosion", "electrical explosion",
            "battery explosion", "lithium battery fire",
            "lithium ion battery explosion", "phone battery fire",
            "e-cigarette explosion", "vape battery fire",
            "hoverboard fire", "scooter battery fire",
            "solar panel fire", "inverter fire",
            "ev battery fire", "electric vehicle fire",
            "tesla fire", "charging station fire",
            "spontaneous combustion", "self heating",
            "oily rag fire", "chemical reaction fire",
            "flash fire", "flashover", "backdraft",
            "firestorm", "fire tornado", "fire whirl",
            "ember attack", "flying ember", "spot fire",
            "first degree burn", "second degree burn",
            "third degree burn", "fourth degree burn",
            "thermal burn", "radiation burn", "friction burn",
            "steam burn severe", "hot liquid burn",
            "contact burn", "hot metal burn", "hot glass burn",
            "sunburn severe", "tanning bed burn",
        ],

        # =====================================================================
        # CRIME, SECURITY & PUBLIC SAFETY THREATS
        # =====================================================================
        "crime_danger": [
            "crime", "criminal", "robbery", "burglary", "theft",
            "kidnapping", "abduction", "hostage", "extortion",
            "dangerous neighborhood", "high-crime area", "gang territory",
            "carjacking", "home invasion", "break-in",
            "security threat", "dangerous person",
            "serial killer", "predator", "stalker",
            "harassment", "intimidation",
            "mugging", "street crime", "purse snatching", "pocket" ,"pick pocket","picking"
            "pickpocketing", "bag theft", "phone snatching",
            "smash and grab", "organized retail theft",
            "shoplifting violent", "store robbery",
            "bank robbery", "armored car robbery",
            "jewelry store heist", "museum heist",
            "armed assault", "knife point robbery",
            "gunpoint robbery", "threatening with weapon",
            "shooting incident", "shots fired",
            "bullet holes", "bullet impact",
            "explosive threat", "bomb threat",
            "suspicious package", "unattended bag",
            "white powder scare", "anthrax scare",
            "mass casualty incident", "terrorist incident",
            "active threat", "lockdown", "shelter in place",
            "evacuation order", "curfew imposed",
            "martial law", "civil emergency",
            "protest turning violent", "crowd crush",
            "stampede", "crowd surge",
            "looting", "rioting", "property destruction",
            "vandalism dangerous", "sabotage",
            "arson criminal", "firebombing criminal",
            "drug related violence", "drug trafficking",
            "turf war", "gang shooting", "drive by",
            "stray bullet", "cross fire",
            "police standoff", "barricade situation",
            "swat deployment", "hostage rescue",
            "fugitive at large", "manhunt",
            "prison break", "escaped prisoner",
            "dangerous fugitive", "wanted criminal",
            "sex offender nearby", "registered offender",
            "peeping tom", "voyeur", "prowler",
            "trespasser dangerous", "intruder",
            "home security breach", "alarm triggered",
            "security camera tampering", "surveillance threat",
        ],

        # =====================================================================
        # ELECTRICAL & ENERGY HAZARDS
        # =====================================================================
        "electrical_hazard": [
            "electrical shock", "electrocution risk", "electric shock",
            "high voltage danger", "live wire exposed",
            "power line down", "downed power line",
            "transformer malfunction", "substation hazard",
            "circuit overload", "electrical overload",
            "short circuit", "ground fault", "arc fault",
            "arc flash hazard", "arc blast",
            "electrical burn severe", "contact burn electrical",
            "faulty wiring", "exposed wiring", "frayed wire",
            "damaged insulation wire", "wire in water",
            "wet electrical hazard", "water and electricity",
            "outlet sparking", "switch sparking",
            "buzzing electrical", "humming electrical",
            "hot electrical panel", "burning smell electrical",
            "overloaded circuit breaker", "tripped breaker",
            "fuse blown", "double tapped breaker",
            "aluminum wiring hazard", "knob and tube wiring",
            "ungrounded outlet", "no ground wire",
            "extension cord overuse", "daisy chain cords",
            "power strip overload", "surge protector failure",
            "generator hazard", "portable generator danger",
            "generator carbon monoxide", "generator electrocution",
            "solar panel electrical hazard",
            "inverter malfunction", "battery bank hazard",
            "capacitor discharge", "stored electrical energy",
            "static electricity discharge", "static spark",
            "lightning protection failure", "lightning strike building",
            "stray voltage", "neutral current hazard",
            "underground cable strike", "cable dig hazard",
            "overhead power line contact", "crane power line",
            "ladder power line contact", "antenna power line",
            "electric fence malfunction", "farm electric hazard",
        ],

        # =====================================================================
        # ENVIRONMENTAL & ECOLOGICAL HAZARDS
        # =====================================================================
        "environmental_hazard": [
            "air quality dangerous", "aqi hazardous",
            "smog severe", "ozone alert", "particulate matter high",
            "pm2.5 dangerous", "pm10 dangerous",
            "wildfire smoke", "volcanic smog", "vog",
            "industrial emission hazard", "factory smoke stack",
            "toxic release", "chemical release",
            "environmental contamination", "soil pollution",
            "groundwater pollution", "aquifer contamination",
            "river contamination", "lake contamination",
            "ocean pollution", "oil spill", "petroleum spill",
            "chemical spill waterway", "industrial runoff",
            "agricultural runoff toxic", "fertilizer runoff",
            "algae bloom toxic", "dead zone ocean",
            "fish kill", "wildlife die-off",
            "invasive species dangerous", "killer bees",
            "africanized bee swarm", "fire ant mound",
            "venomous snake habitat", "bear encounter",
            "mountain lion encounter", "wolf pack encounter",
            "wild boar danger", "moose encounter",
            "coyote aggression", "rabid animal",
            "diseased animal", "dead animal disease risk",
            "bird flu area", "west nile virus area",
            "lyme disease area", "tick borne illness area",
            "mosquito borne disease", "zika area",
            "dengue area", "malaria zone",
            "plague area", "hantavirus area",
            "valley fever area", "coccidioidomycosis",
            "histoplasmosis area", "bat guano hazard",
            "mold exposure", "black mold", "toxic mold",
            "asbestos exposure area", "lead paint area",
            "radon high level", "uranium ore exposure",
            "mine tailings hazard", "slag pile hazard",
            "landfill gas hazard", "methane buildup",
            "sewer gas", "hydrogen sulfide exposure",
            "abandoned well hazard", "uncapped well",
            "abandoned mine hazard", "mine shaft open",
        ],

        # =====================================================================
        # INFRASTRUCTURE & UTILITY HAZARDS
        # =====================================================================
        "infrastructure_hazard": [
            "power outage dangerous", "blackout",
            "grid failure", "electrical grid collapse",
            "water main break", "water system failure",
            "boil water advisory", "water treatment failure",
            "sewage overflow", "sewage backup",
            "gas main rupture", "gas line break",
            "gas odor detected", "mercaptan smell",
            "pipeline rupture", "oil pipeline leak",
            "natural gas pipeline leak", "chemical pipeline",
            "road collapse", "road sinkhole", "road cave-in",
            "bridge unsafe", "bridge weight limit",
            "bridge ice", "bridge flooding",
            "tunnel flooding", "tunnel fire",
            "dam seepage", "dam overtopping",
            "dam failure imminent", "levee overtopping",
            "railway crossing hazard", "train crossing malfunction",
            "signal failure", "traffic light failure",
            "stop sign missing", "road sign missing",
            "guardrail missing", "barrier missing",
            "streetlight outage", "dark intersection",
            "traffic camera failure", "speed camera zone",
            "construction zone hazard", "detour danger",
            "road closed", "washed out road",
            "flooded road", "frozen road",
            "unpaved road hazard", "gravel road loose",
            "steep grade danger", "sharp curve danger",
            "blind corner", "limited sight distance",
            "falling rock zone", "rockslide area",
            "avalanche zone road", "mudslide zone road",
            "wildlife crossing", "animal crossing zone",
            "airport hazard", "runway hazard",
            "port hazard", "dock collapse",
            "pier deterioration", "marina hazard",
            "communication tower hazard", "antenna fall risk",
            "underground utility strike", "digging hazard",
            "buried pipeline hazard", "buried cable hazard",
        ],

        # =====================================================================
        # OUTDOOR, RECREATION & WILDERNESS HAZARDS
        # =====================================================================
        "outdoor_hazard": [
            "hiking danger", "trail hazard", "cliff edge",
            "steep cliff", "unstable cliff edge",
            "rockfall hazard", "loose rock",
            "mountain climbing danger", "rock climbing fall",
            "rope failure", "harness failure", "carabiner failure",
            "avalanche danger zone", "backcountry avalanche",
            "crevasse hazard", "glacier hazard",
            "whiteout mountain", "summit danger",
            "altitude sickness severe", "high altitude pulmonary edema",
            "high altitude cerebral edema",
            "hypothermia wilderness", "exposure risk",
            "lost in wilderness", "search and rescue needed",
            "dehydration wilderness", "water source contaminated",
            "bear attack", "cougar attack", "wolf attack",
            "snake bite wilderness", "venomous creature",
            "quicksand", "bog hazard", "marsh hazard",
            "swift river crossing", "flash flood canyon",
            "slot canyon danger", "box canyon trap",
            "desert heat danger", "desert survival",
            "sandstorm danger", "dust devil",
            "forest hazard", "deadfall tree",
            "widow maker tree", "falling branch",
            "poison ivy", "poison oak", "poison sumac",
            "stinging nettle", "thorny brush",
            "wild animal encounter", "moose attack",
            "bison encounter", "elk encounter",
            "venomous spider outdoors", "scorpion area",
            "camping hazard", "tent fire",
            "campfire spread", "propane stove hazard camping",
            "bear canister needed", "food storage bear area",
            "hunting area danger", "shooting range nearby",
            "off trail danger", "unmarked trail",
            "abandoned mine outdoor", "old mining shaft",
            "cave hazard", "cave in risk",
            "diving hazard", "underwater cave diving",
            "free diving danger", "cliff diving danger",
            "parasailing hazard", "paragliding hazard",
            "zip line malfunction", "bungee cord failure",
            "ski slope hazard", "avalanche ski area",
            "tree well skiing", "cliff drop skiing",
            "snowboard hazard", "terrain park injury",
            "whitewater rafting danger", "kayaking rapids danger",
        ],

        # =====================================================================
        # CHILD & VULNERABLE PERSON SAFETY
        # =====================================================================
        "child_safety": [
            "child in danger", "child endangerment",
            "unsupervised child hazard", "child left alone",
            "hot car child", "child locked in car",
            "child drowning risk", "pool no fence",
            "child pool hazard", "bathtub drowning risk",
            "window fall child", "balcony fall child",
            "stair fall child", "playground injury severe",
            "playground equipment hazard", "swing set collapse",
            "trampoline injury", "bounce house hazard",
            "choking hazard child", "small object choking",
            "button battery ingestion", "magnet ingestion",
            "poison ingestion child", "medication child access",
            "cleaning product child", "cabinet lock missing",
            "gun access child", "firearm unsecured",
            "child car seat missing", "no seatbelt child",
            "child pedestrian danger", "school zone hazard",
            "child bicycle danger", "helmet not worn",
            "bullying severe", "cyberbullying threat",
            "predator threat child", "stranger danger",
            "missing child", "amber alert",
            "child trafficking", "child exploitation",
            "abuse indicators", "neglect indicators",
            "elderly fall risk", "elderly wandering",
            "dementia patient lost", "alzheimer patient danger",
            "disabled person hazard", "wheelchair hazard",
            "mobility aid failure", "oxygen equipment hazard",
            "medical device malfunction", "pacemaker malfunction",
            "insulin pump failure", "ventilator failure",
        ],

        # =====================================================================
        # GENERAL DANGER & HAZARD KEYWORDS
        # =====================================================================
        "general_danger": [
            "danger", "dangerous", "hazard", "hazardous",
            "risk", "risky", "peril", "perilous",
            "threat", "threatening", "unsafe", "unsafe conditions",
            "critical", "critical condition", "emergency",
            "emergency situation", "urgent", "life-threatening",
            "severe", "serious", "fatal", "deadly", "lethal",
            "harmful", "harm", "injurious", "detrimental", "adverse",
            "warning", "caution", "alert", "evacuation",
            "shelter in place", "take cover", "seek safety",
            "high risk area", "danger zone", "restricted area",
            "no entry zone", "prohibited area", "exclusion zone",
            "contaminated area", "quarantine zone",
            "unexploded ordnance", "uxo", "land mine",
            "booby trap", "trip wire", "hidden hazard",
            "unmarked hazard", "invisible danger",
            "impending danger", "imminent threat",
            "clear and present danger", "immediate risk",
            "escalating situation", "deteriorating conditions",
            "worsening situation", "getting worse",
            "out of control", "uncontrolled",
            "unstable situation", "volatile situation",
            "unpredictable", "erratic behavior",
            "mayday", "sos", "distress signal",
            "emergency broadcast", "amber alert signal",
            "silver alert", "blue alert", "red alert",
            "code red", "code blue", "code black",
            "triage", "mass casualty", "disaster response",
            "first responder needed", "paramedic needed",
            "ambulance needed", "fire department needed",
            "police needed", "rescue needed",
            "trapped", "stuck", "stranded", "marooned",
            "isolated", "cut off", "no escape",
            "blocked exit", "no way out", "cornered",
            "survival situation", "life or death",
            "do not enter", "keep out", "stay away",
            "extreme caution", "proceed with caution",
            "at your own risk", "liability",
            "condemned property", "demolition pending",
            "structurally unsound", "load bearing failure",
            "potential collapse", "imminent collapse",
        ],
    }
}


def get_category_keywords(category: str) -> dict:
    """
    Get all keywords for a specific category.

    Args:
        category: Category name (SCAM or DANGER)

    Returns:
        Dictionary of subcategories and their keywords
    """
    if category not in KEYWORDS_DATABASE:
        raise ValueError(f"Unknown category: {category}")
    return KEYWORDS_DATABASE[category]


def get_all_keywords(category: str) -> list:
    """
    Get flattened list of all keywords for a category.

    Args:
        category: Category name (SCAM or DANGER)

    Returns:
        Flat list of all keywords (deduplicated)
    """
    keywords = get_category_keywords(category)
    all_keywords = []
    seen = set()
    for subcat_keywords in keywords.values():
        for kw in subcat_keywords:
            kw_lower = kw.lower().strip()
            if kw_lower not in seen:
                seen.add(kw_lower)
                all_keywords.append(kw)
    return all_keywords


def get_categories() -> list:
    """Get list of available categories"""
    return list(KEYWORDS_DATABASE.keys())


def get_keyword_count() -> dict:
    """Get count of keywords per category and total"""
    counts = {}
    total = 0
    for category in get_categories():
        cat_keywords = get_all_keywords(category)
        counts[category] = len(cat_keywords)
        total += len(cat_keywords)
    counts["TOTAL"] = total
    return counts
